# Go2RTC Configuration for RTSP to WebRTC streaming

# Streams configuration
# Streams will be added dynamically via the web interface
# You can also configure static streams here if needed
streams:
  # camera1 will be configured via web interface
  # Or add static stream here:
  # camera1:
  #   - rtsp://user:pass@192.168.1.100:554/stream

# WebRTC configuration with TURN support
webrtc:
  listen: ":8555"

  # ICE servers configuration (STUN and TURN)
  ice_servers:
    # STUN server
    - urls:
        - "stun:coturn:3478"

    # TURN server (using coturn container)
    - urls:
        - "turn:coturn:3478?transport=udp"
        - "turn:coturn:3478?transport=tcp"
      username: "turnuser"
      credential: "turnpassword"

  # Candidates configuration - replace with your server's public IP
  # candidates:
  #   - stun:8555
  #   - <your-public-ip>:8555

# API configuration
api:
  listen: ":1984"
  # Enable static file serving for web interface
  static_dir: ""

# RTSP server (optional, for re-streaming)
rtsp:
  listen: ":8554"

# Log level: trace, debug, info, warn, error
log:
  level: info
  format: text
